### ISSUE TITLE
problema con crome

### ISSUE THREAD

**Issue by max-08** [fpollicelli/whatsappScraper#2]
Salve Francesca complimenti per lo script, ho un problema con Chrome, ho installato sia Chromedriver che aggiornato Chrome, mi sapresti aiutare? grazie

Exception in thread Thread-2 (getChatLabels):
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xx\Desktop\DIGITAL FORENSICS\whatsappScraper-master\whatsappScraper-master\main.py", line 436, in getChatLabels
    driver = openChrome()

**Comment by fpollicelli** [comment]
Ciao @max-08 ! Anzitutto ti ringrazio! 😁
Purtroppo questa versione non è attualmente mantenuta, ma ho comunque cercato di riprodurre il tuo errore, sembrerebbe essere colpa dei parametri executable_path e service_args passati al webdriver:

`driver = webdriver.Chrome(options=options, executable_path=findChromeDriver(), service_args=args)`

la versione aggiornata di selenium non li prevede, quindi si risolve rimuovendoli:

`driver = webdriver.Chrome(options=options)`

Ho fatto un push di questa modifica e aggiornato la versione di chromedriver presente in questo repository (ora è compatibile con l'ultima versione di Chrome) ma probabilmente incapperai in altri problemi, speriamo in un prossimo futuro di trovare del tempo per aggiornare questo progetto! 😊

Spero di esserti stata utile, grazie ancora per il tuo feedback!

**Comment by max-08** [comment]
Grazie Francesca per la velocità... ho seguito il tuo talk all'hackinbo... ed ho visto anche il tuo nuovo tool FIT.
Ho modificato i parametri ma compaiono altri errori, 

selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 114.0.5735.134 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

Capisco che forse non hai tempo di aggiornarlo, ma è davvero interessante e davvero ben fatto come script.
Grazie ancora..

**Comment by fpollicelli** [comment]
Per questo problema devi scaricare la versione aggiornata di chromedriver e sostituirla con quella che hai nella cartella di progetto, la puoi trovare direttamente qui https://github.com/fpollicelli/whatsappScraper/blob/master/chromedriver.exe
Cercherò di aggiornare lo script entro la prossima settimana e speriamo di riuscire a integrare qualcosa di simile anche in FIT 😊
